# - - - - - - - - - - -
# | Token of your bot |
# - - - - - - - - - - -
bot: ""

# - - - - - - - - - - - -
# | MySQL Configuration |
# - - - - - - - - - - - -
mysql:
  username: "root"
  password: ""
  database: "authentication"
  hostname: "localhost"
